# Copyright (c) 2022 Purple Clay
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# in the Software without restriction, including without limitation the rights
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - id: misspell-codeclimate
    ldflags:
      - -s -w
      - -X github.com/purpleclay/misspell-codeclimate/cmd.version={{.Tag}}
      - -X github.com/purpleclay/misspell-codeclimate/cmd.gitCommit={{.Commit}}
      - -X github.com/purpleclay/misspell-codeclimate/cmd.gitBranch=main
      - -X github.com/purpleclay/misspell-codeclimate/cmd.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"

archives:
  - id: misspell-codeclimate-archive
    format: tar.gz
    name_template: |-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}
    builds:
      - misspell-codeclimate
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  use: github
  filters:
    exclude:
      - "^test"
      - "^chore"
      - "^ci"
  groups:
    - title: "Dependency Updates"
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 30
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 20
    - title: "Documentation Updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 40
    - title: "Other Work"
      order: 99

sboms:
  - artifacts: archive

# Use Keyless experimental signing with cosign, see: https://github.com/sigstore/cosign/blob/main/KEYLESS.md
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"

brews:
  - name: misspell-codeclimate
    tap:
      owner: purpleclay
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/purpleclay/misspell-codeclimate"
    description: "Turn that misspell report into a GitLab compatible codeclimate report"
    license: MIT
    install: |
      bin.install "misspell-codeclimate"

      bash_output = Utils.safe_popen_read(bin/"misspell-codeclimate", "completion", "bash")
      (bash_completion/"misspell-codeclimate").write bash_output

      zsh_output = Utils.safe_popen_read(bin/"misspell-codeclimate", "completion", "zsh")
      (zsh_completion/"_misspell-codeclimate").write zsh_output

      fish_output = Utils.safe_popen_read(bin/"misspell-codeclimate", "completion", "fish")
      (fish_completion/"misspell-codeclimate.fish").write fish_output

      man1.install "manpages/misspell-codeclimate.1.gz"
    test: |
      installed_version = shell_output("#{bin}/misspell-codeclimate version --short 2>&1")
      assert_match "v#{version}", installed_version

scoop:
  bucket:
    owner: purpleclay
    name: scoop-bucket
  homepage: "https://github.com/purpleclay/misspell-codeclimate"
  description: "Turn that misspell report into a GitLab compatible codeclimate report"
  license: MIT

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: "https://github.com/purpleclay/misspell-codeclimate"
    description: "Turn that misspell report into a GitLab compatible codeclimate report"
    maintainer: Purple Clay <purpleclaygh@gmail.com>
    license: MIT
    vendor: Purple Clay
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/misspell-codeclimate.bash
        dst: /usr/share/bash-completion/completions/misspell-codeclimate
        file_info:
          mode: 0644
      - src: ./completions/misspell-codeclimate.fish
        dst: /usr/share/fish/completions/misspell-codeclimate.fish
        file_info:
          mode: 0644
      - src: ./completions/misspell-codeclimate.zsh
        dst: /usr/share/zsh/vendor-completions/_misspell-codeclimate
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/misspell-codeclimate/copyright
        file_info:
          mode: 0644
      - src: ./manpages/misspell-codeclimate.1.gz
        dst: /usr/share/man/man1/misspell-codeclimate.1.gz
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

publishers:
  - name: fury.io
    ids:
      - packages
    env:
      - "FURY_TOKEN={{ .Env.FURY_TOKEN }}"
    cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}

aurs:
  - homepage: "https://github.com/purpleclay/misspell-codeclimate"
    description: "Turn that misspell report into a GitLab compatible codeclimate report"
    maintainers:
      - "Purple Clay <purple clay at gmail dot com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/misspell-codeclimate-bin.git"
    package: |-
      # bin
      install -Dm755 "./misspell-codeclimate" "${pkgdir}/usr/bin/misspell-codeclimate"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/misspell-codeclimate/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/misspell-codeclimate.bash" "${pkgdir}/usr/share/bash-completion/completions/misspell-codeclimate"
      install -Dm644 "./completions/misspell-codeclimate.zsh" "${pkgdir}/usr/share/zsh/site-functions/_misspell-codeclimate"
      install -Dm644 "./completions/misspell-codeclimate.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/misspell-codeclimate.fish"

      # manpages
      install -Dm644 "./manpages/misspell-codeclimate.1.gz" "${pkgdir}/usr/share/man/man1/misspell-codeclimate.1.gz"

release:
  footer: |
    **Full Changelog**: https://github.com/purpleclay/misspell-codeclimate/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## What to do next?

    - Follow us on [Twitter](https://twitter.com/purpleclaydev)
